name: beyond
description: A starting point for Dart libraries or applications.
version: 1.0.0-rc.1
homepage: https://github.com/Meruya-Techhnology/Beyond/tree/main/beyond

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  args: ^2.3.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  collection: ^1.17.0
  get_it: ^7.2.0
  encrypt: ^5.0.1
  postgres: ^2.5.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
