name: beyond_cli
description: A simple command line interface, for initializing Fullstack flutter project (Beyond)
version: 0.0.1
homepage: https://github.com/Meruya-Techhnology/Beyond/tree/main/beyond_cli

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  beyond: main